### ISSUE TITLE
"Your invoice has been uploaded" seems to show/hide alternately when working on invoice

### ISSUE THREAD

**Issue by davedx** [davedx/invoicerunner#25]
There seems to be a small issue with the popover that says "Your invoice has been uploaded..." on the main invoices screen (displayed just after you upload and decide to edit what you've uploaded). If you click repeatedly in e.g. the invoice number input, it will alternately show and hide itself.

I'm not sure what's causing this. It's low priority, but if we could get it to just go away permanently when they start doing anything, that would be great.

**Comment by alinutzaB** [comment]
Ok, I will try to fixed.
